#!/usr/bin/env python
#-*- coding: utf-8 -*-

from bs4 import BeautifulSoup
import requests

def get_lorder_sex(class_name):
    if class_name == ['member_girl_ico']:
        return '女'
    elif class_name == ['nember_boy_ico']:
        return '男'

def get_links(url):
    wb_data = requests.get(url)
    soup = BeautifulSoup(wb_data.text, 'lxml')
    links = soup.select('#page_list > ul > li > a ')
    for link in links:
        href = link.get('href')
        get_detail_info(href)
def get_detail_info(url):
    wb_data = requests.get(url)
    soup = BeautifulSoup(wb_data.text,'lxml')
    titles = soup.select('body > div.wrap.clearfix.con_bg > div.con_l > div.pho_info > h4 > em')
    adds = soup.select('body > div.wrap.clearfix.con_bg > div.con_l > div.pho_info > p > span.pr5')
    prices = soup.select('#pricePart > div.day_l > span')
    imgs = soup.select('#curBigImage')
    holders = soup.select('#floatRightBox > div.js_box.clearfix > div.member_pic > a > img')
    sexs = soup.select('#floatRightBox > div.js_box.clearfix > div.w_240 > h6 > span')

    for title, add, price, img, holder, sex in zip(titles, adds, prices, imgs, holders, sexs):
        data={
            'title':titles.get_text(),
            'add':adds.get_text(),
            'price':prices.get_text(),
            'img':imgs.get('src'),
            'holder':holders.get('src'),
            'sex':get_lorder_sex(sexs.get('class'))
        }
        print(data)
urls = ['http://cq.xiaozhu.com/search-duanzufang-p{}-0/'.format(i) for i in range(1, 6)]
for single_url in urls:
    get_links(single_url)


